name: Build Exynos 850 Kernel for Galaxy A21s

on:
  push:
    branches:
      - master  # or 'main' if that's your default branch
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: master  # Ensure you're using the correct branch (e.g., 'master')

      # Step 2: Install necessary build dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bc \
            git \
            gcc \
            g++ \
            make \
            python3 \
            libncurses5-dev \
            libncursesw5-dev \
            bison \
            flex \
            libssl-dev \
            ccache \
            curl \
            libelf-dev \
            wget \
            unzip

      # Step 3: Download and set up Android NDK (r25b version for kernel builds)
      - name: Set up Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          export NDK_HOME=$PWD/android-ndk-r25b
          export PATH=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      # Step 4: Download and set up the aarch64-linux-android toolchain
      - name: Set up aarch64-linux-android Toolchain
        run: |
          wget https://releases.linaro.org/components/toolchain/binaries/7.5-2019.12/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz
          tar -xf gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz
          export CROSS_COMPILE=$PWD/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-
          export PATH=$PWD/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin:$PATH

      # Step 5: Set up Clang Toolchain
      - name: Set up Clang Toolchain
        run: |
          export PATH=/home/$USER/toolchains/clang/host/linux-x86/clang-r547379/bin:$PATH
          export ARCH=arm64
          export LLVM=1
          export LLVM_IAS=1

      # Step 6: Clone the forked upstream_exynos850 repository
      - name: Clone Forked Upstream Exynos850
        run: |
          git clone https://github.com/21H2/upstream_exynos850.git
          
      # Step 7: Enter Build Directory and Compile Kernel
      - name: Compile Kernel
        run: |
          cd upstream_exynos850
          mkdir -p out
          make ARCH=arm64 O=out CC=clang exynos850-a21snsxx_defconfig
          make ARCH=arm64 O=out CC=clang -j$(nproc)

      # Step 8: Create Boot Image
      - name: Create Boot Image
        run: |
          mkbootimg --kernel out/arch/arm64/boot/Image.gz --ramdisk ramdisk.img --cmdline "console=ttyS0,115200n8" -o out/boot.img

      # Step 9: Upload Boot Image as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot-image
          path: out/boot.img
