name: Build Exynos 850 Kernel for Galaxy A21s

on:
  push:
    branches:
      - master  # Ensure 'master' is the correct default branch
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu runner to build the kernel

    steps:
      # Step 1: Configure Git user configuration
      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      # Step 2: Checkout the repository (adjust branch if necessary)
      - name: Checkout Repository
        uses: actions/checkout@v3  # Make sure you use the latest version
        with:
          ref: master  # Ensure you use the correct branch (e.g., 'master')
          fetch-depth: 2  # Increased depth to avoid issues with shallow clones

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bc \
            git \
            gcc \
            g++ \
            make \
            python3 \
            libncurses5-dev \
            libncursesw5-dev \
            bison \
            flex \
            libssl-dev \
            ccache \
            curl \
            libelf-dev \
            wget \
            unzip

      # Step 4: Set up Android NDK for cross-compilation
      - name: Set up Android NDK
        run: |
          wget https://dl.google.com/linux/direct/android-ndk-r21e-linux-x86_64.zip
          unzip android-ndk-r21e-linux-x86_64.zip
          export NDK_HOME=$PWD/android-ndk-r21e

      # Step 5: Configure the Kernel for Exynos 850 (Galaxy A21s)
      - name: Configure Kernel
        run: |
          cd $GITHUB_WORKSPACE
          make ARCH=arm64 exynos850_defconfig  # Replace with your actual defconfig if needed

      # Step 6: Build the Kernel with the Android NDK toolchain
      - name: Build Kernel
        run: |
          make ARCH=arm64 CROSS_COMPILE=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android- -j$(nproc)

      # Step 7: (Optional) Create Boot Image from the kernel
      - name: Create Boot Image
        run: |
          mkbootimg --kernel arch/arm64/boot/Image.gz --ramdisk ramdisk.img --cmdline "console=ttyS0,115200n8" -o boot.img

      # Step 8: Upload Boot Image as an Artifact
      - name: Upload Boot Image
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: boot-image
          path: boot.img
